export const CITIES = [
  // Major Metropolitan Cities (Top Priority)
  'Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Peshawar', 'Quetta',
  
  // Major Punjab Cities
  'Faisalabad', 'Multan', 'Gujranwala', 'Sialkot', 'Sargodha', 'Bahawalpur', 
  'Sahiwal', 'Gujrat', 'Sheikhupura', 'Jhang', 'Bahawalnagar', 'Sadiqabad',
  'Kasur', 'Okara', 'Rahim Yar Khan', 'Multan', 'Mianwali', 'Vehari',
  'Khanewal', 'Mandi Bahauddin', 'Toba Tek Singh', 'Jhelum', 'Bhalwal',
  'Daska', 'Burewala', 'Hafizabad', 'Chiniot', 'Kamoke', 'Pattoki',
  'Jaranwala', 'Kamalia', 'Renala Khurd', 'Samundri', 'Wazirabad',
  'Murree', 'Mian Channu', 'Bhakkar', 'Lalamusa', 'Shakargarh', 'Layyah',
  'Dinga', 'Pakpattan', 'Arifwala', 'Baddomalhi', 'Gojra', 'Tando Adam',
  'Ahmedpur East', 'Chichawatni', 'Chishtian', 'Mailsi', 'Haroonabad',
  'Hasilpur', 'Bhera', 'Chakwal', 'Pishin', 'Kohat', 'Lakki Marwat',
  'Bannu', 'Karak', 'Tank', 'Hangu', 'Dera Ismail Khan', 'Dera Ghazi Khan',
  'Zhob', 'Loralai', 'Chaman', 'Ghotki', 'Jacobabad', 'Shikarpur',
  'Larkana', 'Nawabshah', 'Khairpur', 'Sukkur', 'Dadu', 'Moro',
  'Shujabad', 'Mehar', 'Kandhkot', 'Kashmor', 'Gambat', 'Warah',
  'Sehwan', 'Kotri', 'Hyderabad', 'Tando Allahyar', 'Tando Muhammad Khan',
  'Matli', 'Turbat', 'Gwadar', 'Pasni', 'Ormara', 'Jiwani',
  'Mastung', 'Kalat', 'Khuzdar', 'Hub', 'Uthal', 'Belapat',
  'Wadh', 'Nushki', 'Dalbandin', 'Taftan', 'Quetta', 'Ziarat',
  'Sibi', 'Harnai', 'Kohlu', 'Duki', 'Barkhan', 'Loralai',
  'Mach', 'Bolan', 'Dera Bugti', 'Dera Murad Jamali', 'Sui', 'Pir Koh',
  'Usta Muhammad', 'Gandakha', 'Jhal Magsi', 'Kachhi', 'Sohbatpur',
  'Leiah', 'Chagai', 'Naseerabad', 'Qambar', 'Shahdadkot',
  'Kallar Syedan', 'Gujar Khan', 'Kahuta', 'Murree', 'Abbottabad',
  'Mansehra', 'Haripur', 'Havelian', 'Batkhela', 'Mardan', 'Swabi',
  'Nowshera', 'Charsadda', 'Timergara', 'Mingora', 'Saidu Sharif',
  'Kabal', 'Chitral', 'Gupis', 'Yasin', 'Shigar', 'Skardu',
  'Kharmang', 'Roundu', 'Ghizer', 'Gakuch', 'Hunza', 'Nagar',
  'Gilgit', 'Diamer', 'Astore', 'Ghanche', 'Kharmang', 'Shigar',
  'Baltistan', 'Rondu', 'Shigar', 'Khaplu', 'Ghanche', 'Skardu',
  'Muzaffarabad', 'Mirpur', 'Rawalakot', 'Kotli', 'Bhimber',
  'Hattian Bala', 'Haveli', 'Bagh', 'Sudhanoti', 'Poonch',
  'Neelum Valley', 'Athmuqam', 'Jhelum Valley', 'Leepa Valley',
  'Haveli', 'Kotli', 'Mirpur', 'Rawalakot', 'Muzaffarabad',
  'Bhimber', 'Pallandri', 'Trarkhel', 'Hajira', 'Sehnsa',
  'Abbottabad', 'Mansehra', 'Haripur', 'Havelian', 'Batkhela',
  'Mardan', 'Swabi', 'Nowshera', 'Charsadda', 'Timergara',
  'Mingora', 'Saidu Sharif', 'Kabal', 'Chitral', 'Gupis',
  'Yasin', 'Shigar', 'Skardu', 'Kharmang', 'Roundu',
  'Ghizer', 'Gakuch', 'Hunza', 'Nagar', 'Gilgit',
  'Diamer', 'Astore', 'Ghanche', 'Kharmang', 'Shigar',
  'Baltistan', 'Rondu', 'Shigar', 'Khaplu', 'Ghanche',
  'Skardu', 'Islamabad', 'Rawalpindi', 'Lahore', 'Faisalabad',
  'Multan', 'Gujranwala', 'Peshawar', 'Quetta', 'Sialkot',
  'Sargodha', 'Bahawalpur', 'Sahiwal', 'Gujrat', 'Sheikhupura',
  'Jhang', 'Bahawalnagar', 'Sadiqabad', 'Kasur', 'Okara',
  'Rahim Yar Khan', 'Mianwali', 'Vehari', 'Khanewal', 'Mandi Bahauddin',
  'Toba Tek Singh', 'Jhelum', 'Bhalwal', 'Daska', 'Burewala',
  'Hafizabad', 'Chiniot', 'Kamoke', 'Pattoki', 'Jaranwala',
  'Kamalia', 'Renala Khurd', 'Samundri', 'Wazirabad', 'Murree',
  'Mian Channu', 'Bhakkar', 'Lalamusa', 'Shakargarh', 'Layyah',
  'Dinga', 'Pakpattan', 'Arifwala', 'Baddomalhi', 'Gojra',
  'Tando Adam', 'Ahmedpur East', 'Chichawatni', 'Chishtian',
  'Mailsi', 'Haroonabad', 'Hasilpur', 'Bhera', 'Chakwal',
  'Attock', 'Fateh Jang', 'Pindigheb', 'Jand', 'Wah Cantonment',
  'Taxila', 'Hazro', 'Hassan Abdal', 'Jhelum', 'Sarai Alamgir',
  'Dina', 'Sohawa', 'Kallar Syedan', 'Gujar Khan', 'Kahuta',
  'Murree', 'Abbottabad', 'Mansehra', 'Haripur', 'Havelian',
  'Batkhela', 'Mardan', 'Swabi', 'Nowshera', 'Charsadda',
  'Timergara', 'Mingora', 'Saidu Sharif', 'Kabal', 'Chitral',
  'Gupis', 'Yasin', 'Shigar', 'Skardu', 'Kharmang',
  'Roundu', 'Ghizer', 'Gakuch', 'Hunza', 'Nagar',
  'Gilgit', 'Diamer', 'Astore', 'Ghanche', 'Kharmang',
  'Shigar', 'Baltistan', 'Rondu', 'Shigar', 'Khaplu',
  'Ghanche', 'Skardu', 'Muzaffarabad', 'Mirpur', 'Rawalakot',
  'Kotli', 'Bhimber', 'Hattian Bala', 'Haveli', 'Bagh',
  'Sudhanoti', 'Poonch', 'Neelum Valley', 'Athmuqam',
  'Jhelum Valley', 'Leepa Valley', 'Haveli', 'Kotli',
  'Mirpur', 'Rawalakot', 'Muzaffarabad', 'Bhimber',
  'Pallandri', 'Trarkhel', 'Hajira', 'Sehnsa'
]

export const CATEGORIES = [
  { id: 'restaurants', name: 'Restaurants & Food', icon: 'restaurant', count: 8420, color: '#f59e0b' },
  { id: 'real-estate', name: 'Real Estate', icon: 'real-estate', count: 5210, color: '#10b981' },
  { id: 'technology', name: 'Technology & IT', icon: 'technology', count: 4890, color: '#60a5fa' },
  { id: 'healthcare', name: 'Healthcare & Medical', icon: 'healthcare', count: 6320, color: '#ef4444' },
  { id: 'education', name: 'Education & Training', icon: 'education', count: 3780, color: '#8b5cf6' },
  { id: 'retail', name: 'Retail & Shopping', icon: 'retail', count: 9100, color: '#ec4899' },
  { id: 'construction', name: 'Construction', icon: 'construction', count: 2340, color: '#f97316' },
  { id: 'automotive', name: 'Automotive', icon: 'automotive', count: 3560, color: '#14b8a6' },
  { id: 'finance', name: 'Finance & Banking', icon: 'finance', count: 1890, color: '#6366f1' },
  { id: 'travel', name: 'Travel & Tourism', icon: 'travel', count: 2670, color: '#0ea5e9' },
  { id: 'beauty', name: 'Beauty & Wellness', icon: 'beauty', count: 4120, color: '#d946ef' },
  { id: 'logistics', name: 'Logistics & Transport', icon: 'logistics', count: 1950, color: '#84cc16' },
]
