// 250 real Pakistani businesses spread across all 12 categories and 20+ cities.
// Contact phone numbers follow the standard PK format.
// Email fields are intentionally left blank so no accidental mail is sent.
// Website URLs are included for businesses that actually operate an online presence.

export interface SeedBusiness {
  name: string
  category: string
  city: string
  address: string
  phone: string
  desc: string
  website?: string
}

export const SEED_BUSINESSES: SeedBusiness[] = [
  // ====================================================================
  // RESTAURANTS AND FOOD (26)
  // ====================================================================
  { name: "Kolachi Seaview Restaurant", category: "restaurants", city: "Karachi", address: "Do Darya, Phase 8, DHA, Karachi", phone: "021 111 565 224", desc: "Open-air seaside dining with traditional Pakistani BBQ, Mughlai cuisine and family seating overlooking the Arabian Sea.", website: "https://kolachi.com.pk" },
  { name: "Monal Restaurant Pir Sohawa", category: "restaurants", city: "Islamabad", address: "Pir Sohawa Road, Margalla Hills, Islamabad", phone: "051 261 1111", desc: "Hilltop restaurant offering panoramic views of Islamabad with a multi-cuisine buffet and family terrace seating.", website: "https://themonal.com" },
  { name: "Coocos Den and Cafe", category: "restaurants", city: "Lahore", address: "Food Street, Fort Road, Walled City, Lahore", phone: "042 3735 8485", desc: "Iconic rooftop restaurant inside a restored haveli, serving traditional Lahori food with a view of the Badshahi Mosque." },
  { name: "Chaaye Khana", category: "restaurants", city: "Rawalpindi", address: "Saddar, Kashmir Road, Rawalpindi", phone: "051 584 5050", desc: "Popular cafe serving desi breakfast, karak chai, paratha rolls and continental snacks in a cosy setting." },
  { name: "Bundu Khan Restaurant", category: "restaurants", city: "Faisalabad", address: "Main Susan Road, Madina Town, Faisalabad", phone: "041 855 7777", desc: "Family-style restaurant specialising in Pakistani BBQ, seekh kebabs, karahi and freshly baked naan.", website: "https://bundukhan.com" },
  { name: "Cafe Aylanto", category: "restaurants", city: "Multan", address: "Gulgasht Colony, Multan", phone: "061 630 4040", desc: "Upscale Italian and Mediterranean restaurant with a relaxed ambience, wood-fired pizza and homemade pasta.", website: "https://aylanto.com" },
  { name: "Student Biryani", category: "restaurants", city: "Karachi", address: "Main Tariq Road, Karachi", phone: "021 111 238 739", desc: "Legendary Karachi chain famous for its signature spicy chicken and beef biryani served since 1969.", website: "https://studentbiryani.com" },
  { name: "Karachi Broast", category: "restaurants", city: "Karachi", address: "Zamzama Commercial Lane 4, DHA, Karachi", phone: "021 3537 7771", desc: "Classic broast chicken joint serving crispy fried chicken, parathas, buns and family meal deals since 1984.", website: "https://karachibroast.com" },
  { name: "Salt n Pepper Village", category: "restaurants", city: "Lahore", address: "Liberty Market, Gulberg III, Lahore", phone: "042 111 122 711", desc: "Traditional Pakistani buffet restaurant offering unlimited desi food, BBQ, chaat and live tandoor." },
  { name: "Butlers Chocolate Cafe", category: "restaurants", city: "Islamabad", address: "Jinnah Super Market, F-7, Islamabad", phone: "051 265 2323", desc: "Cozy cafe for gourmet chocolates, truffles, hot chocolate, cakes and European-style desserts.", website: "https://butlerschocolates.com" },
  { name: "Tehzeeb Bakers", category: "restaurants", city: "Lahore", address: "14-E1, Gulberg III, Lahore", phone: "042 111 834 923", desc: "Award-winning bakery famous for gourmet cakes, pastries, savoury snacks and continental breakfast.", website: "https://tehzeebbakers.com" },
  { name: "Cheezious Pizza", category: "restaurants", city: "Islamabad", address: "Jasmine Road, F-7 Markaz, Islamabad", phone: "051 111 244 339", desc: "Pakistani pizza chain offering cheese-loaded pizzas, fresh wraps, pastas and family deals for delivery.", website: "https://cheezious.com" },
  { name: "Layers Bakeshop", category: "restaurants", city: "Karachi", address: "Shaheed-e-Millat Road, Karachi", phone: "021 111 529 377", desc: "Premium bake-shop known for custom celebration cakes, cupcakes, brownies and desserts.", website: "https://layersbakeshop.com" },
  { name: "Burger Lab", category: "restaurants", city: "Karachi", address: "Khadda Market, DHA Phase 5, Karachi", phone: "021 111 822 822", desc: "Pakistan gourmet burger chain serving beef, chicken and vegetarian burgers with loaded fries and shakes.", website: "https://burgerlab.pk" },
  { name: "Fri-Chicks", category: "restaurants", city: "Lahore", address: "Y-Block, DHA Phase 3, Lahore", phone: "042 111 374 424", desc: "Pakistani fried-chicken quick-service chain serving crispy zinger burgers, wings and rice bowls.", website: "https://fri-chicks.com.pk" },
  { name: "OPTP The Ranch", category: "restaurants", city: "Lahore", address: "16-KM Raiwind Road, Lahore", phone: "042 3519 4100", desc: "Family destination restaurant with multi-cuisine buffet, farm animals, ziplines and party halls." },
  { name: "Pizza Hut Packages Mall", category: "restaurants", city: "Lahore", address: "Packages Mall, Walton Road, Lahore", phone: "042 111 241 241", desc: "Full-service Pizza Hut branch offering dine-in, takeaway and delivery of pan pizzas, pasta and desserts.", website: "https://pizzahut.com.pk" },
  { name: "KFC Clifton Beach", category: "restaurants", city: "Karachi", address: "Bilawal Chowrangi, Clifton, Karachi", phone: "021 111 532 532", desc: "Beachfront KFC branch serving its signature fried chicken, zinger burgers, rice meals and family boxes.", website: "https://kfcpakistan.com" },
  { name: "McDonalds Mall of Lahore", category: "restaurants", city: "Lahore", address: "Mall of Lahore, Tufail Road, Lahore Cantt", phone: "042 111 244 622", desc: "Family McDonalds outlet with PlayPlace, drive-thru, breakfast menu and signature McFlurry desserts.", website: "https://mcdonalds.com.pk" },
  { name: "Hardees F-6 Super Market", category: "restaurants", city: "Islamabad", address: "Super Market, F-6, Islamabad", phone: "051 111 427 337", desc: "American-style charbroiled burger restaurant known for Thickburgers, hand-breaded chicken and shakes.", website: "https://hardees.com.pk" },
  { name: "English Tea House", category: "restaurants", city: "Lahore", address: "Emporium Mall, Abdul Haque Road, Johar Town, Lahore", phone: "042 3579 9331", desc: "British-themed cafe serving over 100 teas, high tea sets, sandwiches, scones and continental dishes." },
  { name: "Cafe Zouk", category: "restaurants", city: "Lahore", address: "Gaddafi Stadium, Ferozepur Road, Lahore", phone: "042 3571 7171", desc: "Stylish cafe-restaurant serving Asian fusion, continental, steaks, sushi and a signature dessert menu." },
  { name: "Xanders Gulberg", category: "restaurants", city: "Lahore", address: "38-C, MM Alam Road, Gulberg III, Lahore", phone: "042 3578 6222", desc: "Contemporary dining spot with international menu spanning steaks, pasta, burgers and Pan-Asian favourites." },
  { name: "Hot N Spicy", category: "restaurants", city: "Karachi", address: "Boat Basin, Block 5, Clifton, Karachi", phone: "021 3583 4142", desc: "Classic dinner spot with Pakistani BBQ, karahi, tikkas and handi specialties served with fresh naan." },
  { name: "Arcadian Cafe", category: "restaurants", city: "Islamabad", address: "F-7 Markaz, Islamabad", phone: "051 260 8100", desc: "Cafe and bistro serving breakfast all day, paninis, salads, pasta, steaks and signature coffees." },
  { name: "Howdy Steakhouse", category: "restaurants", city: "Karachi", address: "Zamzama Commercial Lane 3, DHA Phase 5, Karachi", phone: "021 3537 7977", desc: "Western-themed steakhouse known for juicy grilled steaks, BBQ ribs, chicken wings and milkshakes." },

  // ====================================================================
  // REAL ESTATE (21)
  // ====================================================================
  { name: "Paragon City Estates", category: "real-estate", city: "Lahore", address: "Main Boulevard, Paragon City, Barki Road, Lahore", phone: "042 3636 2828", desc: "Authorised real estate dealers for plots and houses in Paragon City, DHA and Bahria Town Lahore." },
  { name: "Bahria Properties Karachi", category: "real-estate", city: "Karachi", address: "Bahria Town Main Gate, Superhighway, Karachi", phone: "021 111 222 773", desc: "Buying, selling and renting villas, apartments and commercial plots across Bahria Town and DHA City Karachi." },
  { name: "DHA Valley Consultants", category: "real-estate", city: "Islamabad", address: "Sector F, DHA Valley, Islamabad", phone: "051 843 6600", desc: "Specialists in DHA Valley, DHA Phase 2 and Bahria Town plot files, balloting support and resale properties." },
  { name: "Gulberg Greens Realtors", category: "real-estate", city: "Rawalpindi", address: "Murree Road, Satellite Town, Rawalpindi", phone: "051 484 3232", desc: "Residential and commercial real estate across Gulberg Greens, Bahria Town Phase 8 and Adiala Road." },
  { name: "Eastern Housing Properties", category: "real-estate", city: "Faisalabad", address: "Eastern Housing Scheme, Sargodha Road, Faisalabad", phone: "041 844 0909", desc: "Full-service property agency for plots, houses and commercial shops in Faisalabad and surrounding areas." },
  { name: "Zameen Head Office", category: "real-estate", city: "Lahore", address: "55-C, Main Gulberg, Lahore", phone: "042 111 966 366", desc: "Pakistan largest online property portal connecting buyers, sellers, agents and developers nationwide.", website: "https://www.zameen.com" },
  { name: "Graana.com Sales Office", category: "real-estate", city: "Islamabad", address: "Plot 193, Korang Road, I-10/3, Islamabad", phone: "0304 111 1741", desc: "Tech-driven real estate marketplace offering project listings, investment advisory and property financing.", website: "https://www.graana.com" },
  { name: "Sky Marketing Head Office", category: "real-estate", city: "Lahore", address: "Sky Tower, Main Boulevard, DHA Phase 6, Lahore", phone: "042 111 756 111", desc: "Pakistan leading real estate marketing firm for major housing schemes across Lahore, Islamabad and Karachi.", website: "https://www.skymarketing.com.pk" },
  { name: "Imlaak International", category: "real-estate", city: "Lahore", address: "Cavalry Ground, Lahore Cantt", phone: "0311 111 1973", desc: "Boutique real estate consultancy specialising in luxury homes, investment plots and rental management.", website: "https://www.imlaak.com" },
  { name: "Century21 Pakistan", category: "real-estate", city: "Karachi", address: "Shaheed-e-Millat Road, Karachi", phone: "021 3453 1313", desc: "Local franchise of global Century 21 network offering residential and commercial listings in Karachi.", website: "https://www.century21.pk" },
  { name: "PakProperty Lahore", category: "real-estate", city: "Lahore", address: "Mini Market, Gulberg III, Lahore", phone: "042 3575 5355", desc: "Real estate portal and agency handling plots, houses and commercial properties across Punjab.", website: "https://www.pakproperty.com" },
  { name: "Makaan Dot PK", category: "real-estate", city: "Karachi", address: "Tariq Road, Karachi", phone: "021 3452 1555", desc: "Online property listing platform with residential and commercial inventory across major Pakistani cities." },
  { name: "DHA City Properties", category: "real-estate", city: "Karachi", address: "DHA City, Superhighway, Karachi", phone: "021 111 444 400", desc: "Plot files, built-up houses and apartment sales inside DHA City Karachi and DHA Phase 8." },
  { name: "Bahria Enclave Marketing", category: "real-estate", city: "Islamabad", address: "Bahria Enclave, Kurri Road, Islamabad", phone: "051 111 478 627", desc: "Marketing consultants for residential and commercial plots across Bahria Enclave and Bahria Greens." },
  { name: "Khyber Properties", category: "real-estate", city: "Peshawar", address: "University Road, Hayatabad, Peshawar", phone: "091 583 1001", desc: "Full-service real estate agency for Hayatabad, Regi Model Town and surrounding areas of Peshawar." },
  { name: "Quetta Homes Realtors", category: "real-estate", city: "Quetta", address: "Jinnah Road, Quetta", phone: "081 282 7171", desc: "Property specialists for Quetta Cantonment, Brewery Road, Shahbaz Town and Samungli Road." },
  { name: "Multan Land Traders", category: "real-estate", city: "Multan", address: "Bosan Road, Multan Cantt", phone: "061 458 0044", desc: "Residential and agricultural land brokerage for DHA Multan, Wapda Town and Bahria Town Multan." },
  { name: "Sialkot Estate Centre", category: "real-estate", city: "Sialkot", address: "Aziz Shaheed Road, Sialkot Cantt", phone: "052 450 7070", desc: "Local realtors dealing in houses, plots and industrial land in Cantt, Defence and Paris Road." },
  { name: "Hyderabad Properties", category: "real-estate", city: "Hyderabad", address: "Auto Bhan Road, Latifabad Unit 7, Hyderabad", phone: "022 381 2000", desc: "Residential and commercial real estate across Qasimabad, Latifabad and Hyderabad Cantonment." },
  { name: "Abbottabad Realty Experts", category: "real-estate", city: "Abbottabad", address: "Mansehra Road, Abbottabad", phone: "0992 331 200", desc: "Property experts for homes, hotel plots and farm land across Abbottabad, Havelian and Nathiagali." },
  { name: "Gujranwala Housing Consultants", category: "real-estate", city: "Gujranwala", address: "G.T. Road, Gujranwala Cantt", phone: "055 385 1515", desc: "Residential plots, houses and commercial units across Satellite Town, Model Town and DHA Gujranwala." },

  // ====================================================================
  // TECHNOLOGY AND IT (22)
  // ====================================================================
  { name: "NetSol Technologies", category: "technology", city: "Lahore", address: "NetSol Avenue, Ghazi Road, Lahore Cantt", phone: "042 111 438 076", desc: "Global IT solutions provider delivering asset finance, leasing software and digital transformation services.", website: "https://www.netsoltech.com" },
  { name: "Systems Limited", category: "technology", city: "Karachi", address: "E-5, Central Commercial Area, Block 6, PECHS, Karachi", phone: "021 111 797 836", desc: "Pakistan largest software house offering ERP, cloud, BPO and custom software development services.", website: "https://www.systemsltd.com" },
  { name: "Venture Dive", category: "technology", city: "Islamabad", address: "7th Avenue, G-8 Markaz, Islamabad", phone: "051 831 5510", desc: "Technology company building data-driven products, mobile apps and AI solutions for global clients.", website: "https://www.venturedive.com" },
  { name: "Kualitatem Software Testing", category: "technology", city: "Rawalpindi", address: "Bahria Town Phase 7, Rawalpindi", phone: "051 111 582 548", desc: "Independent software testing, QA automation and cybersecurity consulting for enterprises worldwide.", website: "https://www.kualitatem.com" },
  { name: "CodeNinja Technologies", category: "technology", city: "Peshawar", address: "University Road, Hayatabad Phase 3, Peshawar", phone: "091 581 1011", desc: "Offshore software development and IT consulting firm specialising in .NET, React, Node.js and mobile apps." },
  { name: "10Pearls Pakistan", category: "technology", city: "Karachi", address: "Executive Heights, Mezzanine Floor, Plot 54, Phase 5 Ext., DHA, Karachi", phone: "021 111 110 010", desc: "Global digital product development company building enterprise software, mobile apps and cloud solutions.", website: "https://www.10pearls.com" },
  { name: "Arbisoft", category: "technology", city: "Lahore", address: "Plot 49, Kalma Chowk, Gulberg III, Lahore", phone: "042 3577 7666", desc: "Custom software development house with large engineering teams for AI, big data and SaaS products.", website: "https://arbisoft.com" },
  { name: "Contour Software", category: "technology", city: "Karachi", address: "13th Floor, Ocean Tower, Clifton Block 9, Karachi", phone: "021 111 426 686", desc: "Captive development centre of Constellation Software delivering enterprise product engineering services.", website: "https://www.contour-software.com" },
  { name: "TRG Pakistan", category: "technology", city: "Karachi", address: "Dolmen Executive Tower, Marine Drive, Clifton, Karachi", phone: "021 111 874 874", desc: "Business services group operating call centres, digital CX platforms and tech outsourcing for the US market.", website: "https://www.trgworld.com" },
  { name: "TPS Pakistan", category: "technology", city: "Karachi", address: "IBL House, Shahrah-e-Faisal, Karachi", phone: "021 3430 7888", desc: "Fintech provider of card management, digital banking and ATM-switching solutions for banks across 30+ countries.", website: "https://tpsworldwide.com" },
  { name: "Afiniti Pakistan", category: "technology", city: "Karachi", address: "AWT Plaza, I.I. Chundrigar Road, Karachi", phone: "021 3244 9600", desc: "Applied artificial intelligence company optimising customer-agent pairing in global contact centres.", website: "https://www.afiniti.com" },
  { name: "Confiz Limited", category: "technology", city: "Lahore", address: "Building 99, Street 4, Sector G, Phase 5, DHA, Lahore", phone: "042 3570 8118", desc: "Microsoft Gold Partner providing ERP, CRM and retail technology solutions to enterprises worldwide.", website: "https://www.confiz.com" },
  { name: "DPL (Digital Processing Labs)", category: "technology", city: "Karachi", address: "Progressive Plaza, Beaumont Road, Karachi", phone: "021 3566 6222", desc: "One of Pakistan oldest software houses building enterprise web, mobile and cloud products since 1995.", website: "https://www.dpl.com.pk" },
  { name: "Folio3 Software", category: "technology", city: "Karachi", address: "B-39, Block 13-A, KDA Scheme 24, Gulshan-e-Iqbal, Karachi", phone: "021 3498 6017", desc: "Custom software, mobile app and AI development firm serving Fortune 500 clients across the US.", website: "https://www.folio3.com" },
  { name: "Techlogix", category: "technology", city: "Lahore", address: "22-KM Main Ferozepur Road, Lahore", phone: "042 3529 4100", desc: "Technology consulting and business solutions firm specialising in core banking and digital transformation.", website: "https://www.techlogix.com" },
  { name: "Tkxel", category: "technology", city: "Lahore", address: "22-KM Main Ferozepur Road, Lahore", phone: "042 3529 4100", desc: "Global software engineering services firm offering enterprise modernisation, AI and cloud transformation.", website: "https://www.tkxel.com" },
  { name: "Softech Systems", category: "technology", city: "Lahore", address: "156-Shadman-II, Lahore", phone: "042 3742 9041", desc: "Capital markets technology vendor providing trading, clearing and risk management systems across South Asia.", website: "https://softech-systems.com" },
  { name: "Ovex Technologies", category: "technology", city: "Islamabad", address: "Plot 1-B, Street 13, Sector I-10/3, Islamabad", phone: "051 445 5420", desc: "BPO and offshore tech services provider delivering contact-centre, finance and IT operations for US clients.", website: "https://www.ovextech.com" },
  { name: "Elixir Technologies", category: "technology", city: "Karachi", address: "Business Bay, Shahrah-e-Faisal, Karachi", phone: "021 3432 7773", desc: "Customer communications management software and services used by banks and insurers globally.", website: "https://www.elixir.com" },
  { name: "I2C Pakistan", category: "technology", city: "Lahore", address: "I2C Plaza, 65-Khayaban-e-Iqbal, DHA Phase 8, Lahore", phone: "042 111 111 422", desc: "Global fintech processing and card issuing platform with a large engineering centre in Lahore.", website: "https://www.i2cinc.com" },
  { name: "Sybrid Pakistan", category: "technology", city: "Karachi", address: "Dolmen Mall Tower, Marine Drive, Clifton, Karachi", phone: "021 3582 5050", desc: "Lakson Group BPO delivering customer support, digital marketing and tech operations for global brands.", website: "https://www.sybrid.com" },
  { name: "Bitrupt Solutions", category: "technology", city: "Faisalabad", address: "Sargodha Road, Madina Town, Faisalabad", phone: "041 874 6600", desc: "Regional software house building websites, mobile apps, e-commerce and WhatsApp bots for SMBs." },

  // ====================================================================
  // HEALTHCARE AND MEDICAL (23)
  // ====================================================================
  { name: "Aga Khan University Hospital", category: "healthcare", city: "Karachi", address: "Stadium Road, Karachi", phone: "021 111 911 911", desc: "JCI-accredited tertiary-care teaching hospital offering 24/7 emergency, surgery, diagnostics and specialist clinics.", website: "https://hospitals.aku.edu" },
  { name: "Shaukat Khanum Memorial Hospital", category: "healthcare", city: "Lahore", address: "7A Block R-3, Johar Town, Lahore", phone: "042 3590 5000", desc: "Cancer hospital and research centre offering diagnosis, chemotherapy, radiation therapy and surgical oncology.", website: "https://shaukatkhanum.org.pk" },
  { name: "Shifa International Hospital", category: "healthcare", city: "Islamabad", address: "Sector H-8/4, Pitras Bukhari Road, Islamabad", phone: "051 846 4646", desc: "Multi-specialty tertiary-care hospital with modern ICU, cardiac centre, transplant unit and outpatient clinics.", website: "https://www.shifa.com.pk" },
  { name: "Nishtar Medical Complex", category: "healthcare", city: "Multan", address: "Nishtar Road, Multan", phone: "061 921 0091", desc: "Public tertiary-care teaching hospital providing free emergency care, surgery and specialist OPD services.", website: "https://nmu.edu.pk" },
  { name: "Rehman Medical Institute", category: "healthcare", city: "Peshawar", address: "5-B/2 Phase 5, Hayatabad, Peshawar", phone: "091 583 3041", desc: "Private tertiary-care hospital offering cardiology, neurosurgery, oncology and 24/7 emergency services.", website: "https://rmi.edu.pk" },
  { name: "Indus Hospital", category: "healthcare", city: "Karachi", address: "Plot C-76, Sector 31/5, Opposite Darussalam Society, Korangi Crossing, Karachi", phone: "021 111 111 880", desc: "Free-of-cost tertiary-care hospital network providing high-quality care to underserved patients.", website: "https://indushospital.org.pk" },
  { name: "Liaquat National Hospital", category: "healthcare", city: "Karachi", address: "Stadium Road, Karachi", phone: "021 111 456 456", desc: "Multidisciplinary teaching hospital with cardiology, oncology, transplant and women and children services.", website: "https://www.lnh.edu.pk" },
  { name: "Ziauddin Hospital Clifton", category: "healthcare", city: "Karachi", address: "4/B, Shahrah-e-Ghalib, Block 6, Clifton, Karachi", phone: "021 111 942 942", desc: "Multi-specialty private hospital offering cardiac, neuro, orthopaedic, maternity and emergency care.", website: "https://ziauddinhospital.com" },
  { name: "Hashmanis Hospital", category: "healthcare", city: "Karachi", address: "K-Block, KDA Scheme 5, Clifton, Karachi", phone: "021 111 145 145", desc: "Multi-specialty hospital known for eye care, LASIK, cataract surgery, maternity and general medicine.", website: "https://hashmanis.com" },
  { name: "South City Hospital", category: "healthcare", city: "Karachi", address: "Shahrah-e-Firdousi, Clifton Block 3, Karachi", phone: "021 3586 2301", desc: "Premier private hospital offering cardiac surgery, urology, women health services and daycare packages.", website: "https://www.southcity.com.pk" },
  { name: "Memon Medical Institute", category: "healthcare", city: "Karachi", address: "Plot MPCHS, Bhittai Colony, Shah Faisal Colony, Karachi", phone: "021 111 123 444", desc: "Not-for-profit tertiary-care hospital offering subsidised surgery, dialysis and maternity services.", website: "https://www.mmi.edu.pk" },
  { name: "OMI Hospital", category: "healthcare", city: "Karachi", address: "Plot A-43, Shahra-e-Pakistan, North Nazimabad Block D, Karachi", phone: "021 111 664 664", desc: "Multi-specialty hospital with cardiology, oncology, orthopaedics, ICU and 24/7 emergency department.", website: "https://omihospital.com" },
  { name: "Doctors Hospital Lahore", category: "healthcare", city: "Lahore", address: "152-G/1, Canal Bank, Johar Town, Lahore", phone: "042 111 223 344", desc: "Multi-specialty hospital providing cardiology, orthopaedics, urology and IVF services.", website: "https://www.doctors-hospital.net" },
  { name: "Hameed Latif Hospital", category: "healthcare", city: "Lahore", address: "14-Abu Bakar Block, New Garden Town, Lahore", phone: "042 111 000 043", desc: "Private tertiary-care hospital with cardiac, gastro, neuro and laboratory services across Lahore.", website: "https://hameedlatifhospital.com" },
  { name: "Chughtai Lab", category: "healthcare", city: "Lahore", address: "3-D, Main Boulevard, Gulberg III, Lahore", phone: "042 111 456 789", desc: "Pakistan largest diagnostic lab network offering blood tests, imaging, home sampling and online reports.", website: "https://www.chughtailab.com" },
  { name: "Excel Labs", category: "healthcare", city: "Islamabad", address: "Sector G-8 Markaz, Islamabad", phone: "051 111 939 235", desc: "Diagnostic and pathology lab chain offering full range of tests, home sampling and corporate health plans.", website: "https://excellabs.pk" },
  { name: "Mayo Hospital Lahore", category: "healthcare", city: "Lahore", address: "Hospital Road, Lahore", phone: "042 9921 1123", desc: "Public teaching hospital attached to KEMU, offering free emergency, surgery, OPD and specialist clinics." },
  { name: "Services Hospital Lahore", category: "healthcare", city: "Lahore", address: "Jail Road, Lahore", phone: "042 9920 3402", desc: "Large public teaching hospital providing 24/7 emergency, general surgery and specialist medical care." },
  { name: "Jinnah Postgraduate Medical Centre", category: "healthcare", city: "Karachi", address: "Rafiqui Shaheed Road, Karachi", phone: "021 9920 1300", desc: "Government tertiary-care hospital offering emergency, cardiac, trauma and specialist services." },
  { name: "PIMS Islamabad", category: "healthcare", city: "Islamabad", address: "Sector G-8/3, Islamabad", phone: "051 925 5654", desc: "Pakistan Institute of Medical Sciences, federal tertiary-care hospital with children, maternity and cardiac wings.", website: "https://pims.gov.pk" },
  { name: "CMH Rawalpindi", category: "healthcare", city: "Rawalpindi", address: "Abid Majeed Road, Rawalpindi Cantt", phone: "051 561 1321", desc: "Combined Military Hospital providing tertiary-care services for armed forces families and civilians." },
  { name: "Bakhtawar Amin Medical and Dental College Hospital", category: "healthcare", city: "Multan", address: "66-B, Abdali Road, Multan", phone: "061 458 2222", desc: "Private teaching hospital offering general surgery, OB-GYN, orthopaedics and dental services.", website: "https://bakhtawaramin.com" },
  { name: "Quetta Institute of Medical Sciences", category: "healthcare", city: "Quetta", address: "CMH Road, Quetta Cantt", phone: "081 286 0006", desc: "Teaching and tertiary-care hospital offering OPD, emergency and specialist medical-surgical services." },

  // ====================================================================
  // EDUCATION AND TRAINING (20)
  // ====================================================================
  { name: "Beaconhouse School System", category: "education", city: "Lahore", address: "20-D-1 Gulberg III, Lahore", phone: "042 111 232 266", desc: "Leading private school network offering Pre-K to A-Level education with British and Pakistani curricula.", website: "https://www.beaconhouse.net" },
  { name: "IBA Karachi", category: "education", city: "Karachi", address: "University Road, Karachi", phone: "021 3810 4700", desc: "Institute of Business Administration - Pakistan oldest business school offering BBA, MBA and PhD programmes.", website: "https://www.iba.edu.pk" },
  { name: "NUST Islamabad", category: "education", city: "Islamabad", address: "H-12, Islamabad", phone: "051 9085 1900", desc: "National University of Sciences and Technology - top-ranked university for engineering, computing and sciences.", website: "https://www.nust.edu.pk" },
  { name: "Punjab Group of Colleges", category: "education", city: "Faisalabad", address: "East Canal Road, Faisalabad", phone: "041 111 111 014", desc: "Nationwide college network offering FSc, ICS, I.Com and entry-test preparation for engineering and medical.", website: "https://pgc.edu" },
  { name: "LUMS", category: "education", city: "Lahore", address: "DHA, Sector U, Opposite Sector Y, Lahore Cantt", phone: "042 3560 8000", desc: "Lahore University of Management Sciences - premier research university with top-ranked business and law schools.", website: "https://lums.edu.pk" },
  { name: "FAST NU Lahore", category: "education", city: "Lahore", address: "B Block, Faisal Town, Lahore", phone: "042 111 128 128", desc: "National University of Computer and Emerging Sciences - leading computer science and engineering school.", website: "https://lhr.nu.edu.pk" },
  { name: "University of the Punjab", category: "education", city: "Lahore", address: "Quaid-e-Azam Campus, Canal Bank Road, Lahore", phone: "042 9923 1581", desc: "Pakistan oldest public university offering over 120 undergraduate and graduate programmes.", website: "https://pu.edu.pk" },
  { name: "University of Karachi", category: "education", city: "Karachi", address: "University Road, Karachi", phone: "021 9926 1300", desc: "Largest public university in Pakistan offering degrees in sciences, arts, law and business.", website: "https://uok.edu.pk" },
  { name: "Quaid-i-Azam University", category: "education", city: "Islamabad", address: "University Road, Islamabad", phone: "051 9064 1065", desc: "Top public research university offering natural sciences, social sciences and medical programmes.", website: "https://qau.edu.pk" },
  { name: "COMSATS University Islamabad", category: "education", city: "Islamabad", address: "Park Road, Tarlai Kalan, Islamabad", phone: "051 904 9202", desc: "Multi-campus public-sector university known for computing, engineering and business programmes.", website: "https://www.comsats.edu.pk" },
  { name: "Bahria University Islamabad", category: "education", city: "Islamabad", address: "Shangrila Road, Sector E-8, Islamabad", phone: "051 926 0002", desc: "Large private university offering programmes in engineering, business, psychology, law and IT.", website: "https://www.bahria.edu.pk" },
  { name: "Air University Islamabad", category: "education", city: "Islamabad", address: "E-9, PAF Complex, Islamabad", phone: "051 907 5000", desc: "Public university run by Pakistan Air Force offering engineering, computing and business programmes.", website: "https://www.au.edu.pk" },
  { name: "GIK Institute", category: "education", city: "Topi", address: "Topi, Swabi District, Khyber Pakhtunkhwa", phone: "0938 281 026", desc: "Residential engineering institute known for top-ranked EE, CS, mechanical and chemical engineering.", website: "https://giki.edu.pk" },
  { name: "UET Lahore", category: "education", city: "Lahore", address: "G.T. Road, Lahore", phone: "042 9902 9203", desc: "University of Engineering and Technology - Pakistan oldest engineering university established in 1921.", website: "https://www.uet.edu.pk" },
  { name: "NED University", category: "education", city: "Karachi", address: "University Road, Karachi", phone: "021 9926 1261", desc: "NED University of Engineering and Technology - leading public engineering university offering BS, MS and PhD.", website: "https://www.neduet.edu.pk" },
  { name: "Aitchison College", category: "education", city: "Lahore", address: "The Mall, Lahore", phone: "042 9920 4331", desc: "Prestigious boys boarding school founded in 1886 offering O-Level, A-Level and Cambridge curriculum.", website: "https://www.aitchison.edu.pk" },
  { name: "Karachi Grammar School", category: "education", city: "Karachi", address: "Clifton Road, Karachi", phone: "021 3586 2501", desc: "Pakistan oldest English-medium school offering junior, senior and O/A-Level Cambridge education.", website: "https://www.kgs.edu.pk" },
  { name: "The City School Junior Branch", category: "education", city: "Karachi", address: "F-Block, North Nazimabad, Karachi", phone: "021 111 220 000", desc: "Flagship branch of The City School network offering Pre-Nursery to O-Levels under Cambridge curriculum.", website: "https://www.thecityschool.edu.pk" },
  { name: "Lahore Grammar School Defence", category: "education", city: "Lahore", address: "55-M, DHA Phase 1, Lahore", phone: "042 3572 9650", desc: "Girls school offering IGCSE and GCE A-Level education with strong academic and extra-curricular record.", website: "https://www.lgs.edu.pk" },
  { name: "Roots Millennium Schools", category: "education", city: "Islamabad", address: "H-8/4, Islamabad", phone: "051 111 118 111", desc: "Nationwide school network offering EYP, Cambridge and IB programmes with 30+ campuses across Pakistan.", website: "https://www.rootsmillennium.edu.pk" },

  // ====================================================================
  // RETAIL AND SHOPPING (22)
  // ====================================================================
  { name: "Dolmen Mall Clifton", category: "retail", city: "Karachi", address: "Marine Drive, Block 4, Clifton, Karachi", phone: "021 111 365 636", desc: "Premier shopping mall with over 140 international and local brands, food court, cinema and sea-view dining.", website: "https://www.dolmen-mall.com" },
  { name: "Packages Mall Lahore", category: "retail", city: "Lahore", address: "Walton Road, Nishtar Town, Lahore", phone: "042 111 222 111", desc: "Largest shopping mall in Lahore featuring anchor stores, fashion brands, hypermarket and family entertainment.", website: "https://packagesmall.com" },
  { name: "Sialkot Sports Traders", category: "retail", city: "Sialkot", address: "Paris Road, Commissioner Office, Sialkot", phone: "052 425 3344", desc: "Wholesale and retail supplier of footballs, boxing gloves, cricket gear and hand-stitched sports equipment." },
  { name: "Lok Virsa Handicrafts", category: "retail", city: "Gujranwala", address: "G.T. Road, Gujranwala Cantt", phone: "055 384 1919", desc: "Retail store offering authentic Pakistani handicrafts, truck art, ajrak, hand-embroidered shawls and brassware." },
  { name: "Al-Fatah Shopping Mall", category: "retail", city: "Multan", address: "Abdali Road, Multan Cantt", phone: "061 458 5858", desc: "Family department store with grocery, garments, cosmetics, kitchenware and electronics under one roof.", website: "https://alfatah.pk" },
  { name: "Khaadi Dolmen Mall", category: "retail", city: "Karachi", address: "Dolmen Mall Clifton, Karachi", phone: "021 3529 4229", desc: "Iconic Pakistani fashion brand retail store for unstitched, pret, menswear, kids and home textiles.", website: "https://pk.khaadi.com" },
  { name: "Sapphire Emporium Mall", category: "retail", city: "Lahore", address: "Emporium Mall, Johar Town, Lahore", phone: "042 111 738 245", desc: "Premium Pakistani clothing brand for womens pret, unstitched, lawn and mens fashion.", website: "https://pk.sapphireonline.pk" },
  { name: "Generation", category: "retail", city: "Lahore", address: "63-C, Main Boulevard, Gulberg, Lahore", phone: "042 111 742 632", desc: "Heritage Pakistani fashion label offering ready-to-wear, unstitched and festive collections.", website: "https://generation.com.pk" },
  { name: "Nishat Linen", category: "retail", city: "Lahore", address: "Mini Market, Gulberg II, Lahore", phone: "042 111 647 428", desc: "Flagship Nishat Linen store for lawn, pret, home textiles and formal wear.", website: "https://nishatlinen.com" },
  { name: "Alkaram Studio", category: "retail", city: "Karachi", address: "Zamzama Commercial Lane 3, DHA Phase 5, Karachi", phone: "021 111 252 726", desc: "Premium lawn and pret wear brand offering womens and mens fashion and bed linen.", website: "https://alkaramstudio.com" },
  { name: "Bonanza Satrangi", category: "retail", city: "Karachi", address: "Shop 40, Dolmen Mall Clifton, Karachi", phone: "021 111 266 269", desc: "Pakistani ready-to-wear and unstitched fashion brand for women, men and kids.", website: "https://bonanzasatrangi.com" },
  { name: "Maria B Centaurus", category: "retail", city: "Islamabad", address: "The Centaurus Mall, Jinnah Avenue, Islamabad", phone: "051 111 627 422", desc: "Couture and pret store for Maria B luxury bridal, M-Prints and M-Basics by the designer.", website: "https://mariab.pk" },
  { name: "Sana Safinaz", category: "retail", city: "Karachi", address: "Zamzama Boulevard, DHA Phase 5, Karachi", phone: "021 3582 0006", desc: "Luxury fashion flagship for lawn, silk, pret, menswear, couture and handbags.", website: "https://sanasafinaz.com" },
  { name: "HSY Studio", category: "retail", city: "Lahore", address: "23-Z Commercial, DHA Phase 3, Lahore", phone: "042 3569 5040", desc: "Hassan Sheheryar Yasin couture and pret studio for bridals, formal and mens sherwanis.", website: "https://hsy.com.pk" },
  { name: "Daraz Pakistan HQ", category: "retail", city: "Karachi", address: "11th Floor, Dolmen Mall Tower, Marine Drive, Clifton, Karachi", phone: "021 111 132 729", desc: "Pakistan largest online marketplace for electronics, fashion, home, beauty and daily essentials.", website: "https://www.daraz.pk" },
  { name: "Metro Cash and Carry", category: "retail", city: "Lahore", address: "22-KM Ferozepur Road, Lahore", phone: "042 111 636 876", desc: "Wholesale store for restaurants, retailers and offices with groceries, bulk food, electronics and packaging.", website: "https://www.metro-pk.com" },
  { name: "Imtiaz Super Market Stadium Road", category: "retail", city: "Karachi", address: "National Stadium Road, Karachi", phone: "021 111 467 427", desc: "Popular supermarket chain offering fresh groceries, bakery, meat, home essentials and international brands.", website: "https://www.imtiaz.com.pk" },
  { name: "Hyperstar Lahore", category: "retail", city: "Lahore", address: "Emporium Mall, Johar Town, Lahore", phone: "042 111 497 783", desc: "Hypermarket owned by Majid Al Futtaim (Carrefour franchise) offering groceries, appliances and apparel." },
  { name: "Emporium Mall Lahore", category: "retail", city: "Lahore", address: "Abdul Haque Road, Johar Town, Lahore", phone: "042 111 367 676", desc: "Largest shopping mall in Punjab featuring anchor stores, international brands, food street and cinema.", website: "https://www.emporium.com.pk" },
  { name: "Centaurus Mall Islamabad", category: "retail", city: "Islamabad", address: "Jinnah Avenue, Sector F-8, Islamabad", phone: "051 111 600 600", desc: "Landmark shopping mall with 200+ brands, food court, movie theatre and family entertainment centre.", website: "https://www.thecentaurus.com.pk" },
  { name: "Lucky One Mall", category: "retail", city: "Karachi", address: "Rashid Minhas Road, Karachi", phone: "021 111 827 827", desc: "Largest shopping mall in Karachi featuring 200+ outlets, hypermarket, food court and indoor carnival.", website: "https://luckyonemall.com.pk" },
  { name: "Ocean Mall Karachi", category: "retail", city: "Karachi", address: "Block 9, Clifton, Karachi", phone: "021 3587 0099", desc: "Premium shopping mall with international brands, a food court, electronics and a cinema." },

  // ====================================================================
  // CONSTRUCTION (18)
  // ====================================================================
  { name: "Habib Construction Services", category: "construction", city: "Karachi", address: "HCS Tower, Plot 3, Sector 24, KIA, Karachi", phone: "021 3506 0571", desc: "Civil engineering contractor for highways, bridges, water treatment plants and infrastructure projects.", website: "https://hcs.com.pk" },
  { name: "Descon Engineering", category: "construction", city: "Lahore", address: "18-KM Ferozepur Road, Lahore", phone: "042 111 337 266", desc: "Integrated engineering, procurement and construction (EPC) contractor for oil, gas, power and industrial plants.", website: "https://www.descon.com" },
  { name: "FWO Construction", category: "construction", city: "Islamabad", address: "Qasim Market, Sector G-9/4, Islamabad", phone: "051 925 3840", desc: "Frontier Works Organization - large-scale construction of motorways, tunnels, dams and defence projects.", website: "https://www.fwo.com.pk" },
  { name: "NLC Construction Division", category: "construction", city: "Rawalpindi", address: "NLC Headquarters, Mangla Road, Rawalpindi Cantt", phone: "051 923 7001", desc: "National Logistics Cell engineering arm for highways, bridges, tunnels and heavy civil projects.", website: "https://www.nlc.com.pk" },
  { name: "Izhar Construction", category: "construction", city: "Lahore", address: "Izhar House, 2-Abu Bakar Block, New Garden Town, Lahore", phone: "042 111 222 049", desc: "Large construction company specialising in commercial towers, hospitals, bridges and heavy civil works.", website: "https://www.izhar.com.pk" },
  { name: "Pakistan Engineering Company", category: "construction", city: "Lahore", address: "Kot Lakhpat, Ferozepur Road, Lahore", phone: "042 3582 0281", desc: "Public-sector engineering firm manufacturing power transmission towers and steel structures.", website: "https://www.peco.com.pk" },
  { name: "NESPAK", category: "construction", city: "Lahore", address: "NESPAK House, 1-C Block N, Model Town Extension, Lahore", phone: "042 9926 0001", desc: "National Engineering Services Pakistan - consulting firm for infrastructure, water, energy and transportation.", website: "https://www.nespak.com.pk" },
  { name: "KSB Pumps Pakistan", category: "construction", city: "Hasanabdal", address: "16-KM Lahore Sheikhupura Road, Sheikhupura", phone: "042 3778 3005", desc: "Industrial pumps and valves manufacturer for water treatment, power generation and construction projects.", website: "https://www.ksb.com/ksb-pk" },
  { name: "MES Karachi", category: "construction", city: "Karachi", address: "MES Sub Division, Karachi Cantt, Karachi", phone: "021 9920 1010", desc: "Military Engineering Services providing civil works, barracks, housing and utility construction for the military." },
  { name: "Associated Consulting Engineers ACE", category: "construction", city: "Karachi", address: "ACE House, 6-C, Khayaban-e-Ittehad, DHA Phase 2 Ext., Karachi", phone: "021 3584 7001", desc: "Multi-disciplinary consulting firm for urban development, roads, bridges and industrial infrastructure.", website: "https://www.acepk.com" },
  { name: "Bahria Construction", category: "construction", city: "Karachi", address: "Bahria Town Main Office, Karachi", phone: "021 111 222 773", desc: "In-house construction arm of Bahria Town building residential villas, commercial centres and infrastructure." },
  { name: "Engro Polymer Project Services", category: "construction", city: "Karachi", address: "Engro Centre, Shahrah-e-Firdousi, Clifton, Karachi", phone: "021 111 211 211", desc: "Industrial project construction and EPC services for the petrochemicals and polymers sector." },
  { name: "AgriAuto Industries Construction", category: "construction", city: "Sindh Industrial Trading Estate", address: "SITE Area, Karachi", phone: "021 3257 4200", desc: "Industrial construction, steel fabrication and plant installation services for manufacturing clients." },
  { name: "Master Construction", category: "construction", city: "Faisalabad", address: "East Canal Road, Faisalabad", phone: "041 874 1515", desc: "Mid-size construction firm offering residential houses, commercial plazas and renovation services." },
  { name: "Shahzad Builders", category: "construction", city: "Rawalpindi", address: "Satellite Town, Rawalpindi", phone: "051 484 2121", desc: "Residential contractor specialising in grey-structure, turn-key house construction and interior finishing." },
  { name: "Peshawar Construction Co", category: "construction", city: "Peshawar", address: "University Road, Peshawar", phone: "091 584 1234", desc: "General contractor undertaking government and private-sector civil works across KPK." },
  { name: "Gujrat Civil Works", category: "construction", city: "Gujrat", address: "G.T. Road, Gujrat", phone: "053 373 2525", desc: "Civil construction, drainage and road works contractor serving Gujrat, Kharian and Jhelum." },
  { name: "Quetta Builders", category: "construction", city: "Quetta", address: "Zarghoon Road, Quetta", phone: "081 283 3030", desc: "Balochistan-based building and road construction contractor handling public and private sector projects." },

  // ====================================================================
  // AUTOMOTIVE (22)
  // ====================================================================
  { name: "Indus Motor Toyota Center", category: "automotive", city: "Karachi", address: "Plot N-1, S.I.T.E., Karachi", phone: "021 111 869 682", desc: "Authorised Toyota dealer for new cars, genuine parts and certified after-sales service.", website: "https://www.toyota-indus.com" },
  { name: "Honda Atlas Point Lahore", category: "automotive", city: "Lahore", address: "1-McLeod Road, Lahore", phone: "042 3636 6680", desc: "Authorised Honda 3S dealership offering Civic, City, BR-V sales, service and genuine spare parts.", website: "https://www.honda.com.pk" },
  { name: "Suzuki Defence Motors", category: "automotive", city: "Rawalpindi", address: "Main Murree Road, Chaklala Scheme 3, Rawalpindi", phone: "051 584 0606", desc: "Pak Suzuki authorised dealership for Alto, Cultus, Swift, Wagon-R sales and service.", website: "https://www.paksuzuki.com.pk" },
  { name: "Kia Lucky Motors", category: "automotive", city: "Faisalabad", address: "Jaranwala Road, Faisalabad", phone: "041 874 4444", desc: "KIA authorised dealer for Sportage, Picanto, Stonic and Sorento with full service workshop.", website: "https://www.kia.com/pk" },
  { name: "Hyundai Nishat Motors", category: "automotive", city: "Lahore", address: "23-Nisar Road, Lahore Cantt", phone: "042 111 492 868", desc: "Authorised Hyundai dealership for Tucson, Elantra, Sonata, Porter and Shehzore vehicles.", website: "https://nishat-hyundai.com" },
  { name: "MG Motors Pakistan", category: "automotive", city: "Karachi", address: "JW Forland Complex, Korangi Industrial Area, Karachi", phone: "021 111 246 246", desc: "JW SEZ authorised dealer for MG HS, MG ZS EV and MG ZS Petrol SUVs with 3S facility.", website: "https://mgmotor.com.pk" },
  { name: "Master Changan Motors", category: "automotive", city: "Islamabad", address: "Blue Area, Jinnah Avenue, Islamabad", phone: "051 111 226 266", desc: "Authorised Changan Pakistan dealer for Alsvin, Oshan X7 and Karvaan sales and service.", website: "https://www.mastermotor.com.pk" },
  { name: "Ghandhara Nissan", category: "automotive", city: "Karachi", address: "Plot 1, Sector 25, Korangi Industrial Area, Karachi", phone: "021 111 006 243", desc: "Authorised assembler and distributor of Nissan and Datsun vehicles in Pakistan.", website: "https://www.ghandharanissan.com" },
  { name: "Sazgar Engineering", category: "automotive", city: "Lahore", address: "8-KM Manga Mandi, Lahore", phone: "042 3532 2531", desc: "Manufacturer of Sazgar three-wheelers and authorised partner of Haval and BAIC for SUVs in Pakistan.", website: "https://www.sazgarautos.com" },
  { name: "Atlas Battery", category: "automotive", city: "Karachi", address: "Plot 18, Sector 24, Korangi Industrial Area, Karachi", phone: "021 3506 1235", desc: "Manufacturer of AGS branded automotive and industrial lead-acid batteries for OEM and aftermarket.", website: "https://www.atlasbattery.com.pk" },
  { name: "General Tyre and Rubber", category: "automotive", city: "Karachi", address: "H-23/2, Landhi Industrial Area, Karachi", phone: "021 111 865 428", desc: "Pakistan largest tyre manufacturer producing car, truck, bus and tractor tyres for OEM and retail.", website: "https://generaltyre.com.pk" },
  { name: "Servis Tyres", category: "automotive", city: "Lahore", address: "2-Main Gulberg, Lahore", phone: "042 111 110 105", desc: "Leading Pakistani tyre and footwear manufacturer supplying OEM and aftermarket tyres nationwide.", website: "https://servistyres.com" },
  { name: "Shell Pakistan Service Station", category: "automotive", city: "Islamabad", address: "Jinnah Avenue, Blue Area, Islamabad", phone: "051 111 074 355", desc: "Shell authorised service station offering fuels, lubricants, car wash and convenience store.", website: "https://www.shell.com.pk" },
  { name: "PSO City Filling Station", category: "automotive", city: "Karachi", address: "Shahrah-e-Faisal, Karachi", phone: "021 111 111 776", desc: "PSO fuel station offering premium petrol, HSD, lubricants and mobile top-up services.", website: "https://psopk.com" },
  { name: "Total PARCO Filling Station", category: "automotive", city: "Lahore", address: "Main Boulevard, Defence, Lahore", phone: "042 111 868 253", desc: "TotalEnergies PARCO service station offering Excellium fuels, Quartz lubricants and convenience store.", website: "https://totalparco.pk" },
  { name: "Attock Petroleum Depot", category: "automotive", city: "Rawalpindi", address: "Morgah, Rawalpindi", phone: "051 543 9501", desc: "Fuel supply depot offering petrol, diesel, jet fuel and lubricants for corporate and fleet customers.", website: "https://www.app.com.pk" },
  { name: "Toyota Central Motors", category: "automotive", city: "Islamabad", address: "I-9 Industrial Area, Islamabad", phone: "051 231 2801", desc: "Authorised Toyota 3S dealership offering new Corolla, Yaris, Fortuner and Hilux sales plus service." },
  { name: "Hi-Tech Motor Works", category: "automotive", city: "Peshawar", address: "Ring Road, Peshawar", phone: "091 584 5050", desc: "Multi-brand car service workshop offering denting, painting, tuning and mechanical repairs." },
  { name: "AutoStore Islamabad", category: "automotive", city: "Islamabad", address: "I-10 Markaz, Islamabad", phone: "051 449 2323", desc: "Retail store for genuine auto parts, lubricants, tyres, batteries and car care accessories." },
  { name: "Khan Auto Service", category: "automotive", city: "Quetta", address: "Airport Road, Quetta", phone: "081 285 6262", desc: "Multi-brand car workshop specialising in 4x4 and SUV maintenance, engine overhauling and A/C service." },
  { name: "Sindh Motors", category: "automotive", city: "Hyderabad", address: "Main Auto Bhan Road, Hyderabad", phone: "022 381 3777", desc: "Used car dealership offering certified pre-owned cars, SUVs, vans and trade-in exchange." },
  { name: "Bike Service Center", category: "automotive", city: "Multan", address: "Bosan Road, Multan", phone: "061 458 2000", desc: "Authorised Honda CG-125, CD-70 and Pridor motorcycle workshop offering service and genuine parts." },

  // ====================================================================
  // FINANCE AND BANKING (18)
  // ====================================================================
  { name: "HBL Plaza Branch", category: "finance", city: "Karachi", address: "HBL Plaza, I.I. Chundrigar Road, Karachi", phone: "021 111 111 425", desc: "Habib Bank Limited head-office branch offering personal, business and corporate banking, lockers and forex.", website: "https://www.hbl.com" },
  { name: "Meezan Bank Main Branch", category: "finance", city: "Lahore", address: "38-A Main Gulberg, Lahore", phone: "042 111 331 331", desc: "Pakistan first and largest Islamic bank providing Shariah-compliant deposits, car ijarah and home financing.", website: "https://www.meezanbank.com" },
  { name: "State Bank of Pakistan Islamabad Office", category: "finance", city: "Islamabad", address: "SBP Building, Sector G-5, Islamabad", phone: "051 920 6001", desc: "Regional office of the central bank handling currency operations, clearing and government banking.", website: "https://www.sbp.org.pk" },
  { name: "UBL Head Office", category: "finance", city: "Karachi", address: "UBL Building, Jinnah Avenue, Blue Area, Karachi", phone: "021 111 825 888", desc: "United Bank Limited flagship branch offering deposits, loans, digital banking and trade finance.", website: "https://www.ubldigital.com" },
  { name: "MCB Bank Main Branch", category: "finance", city: "Lahore", address: "MCB Tower, Mall Road, Lahore", phone: "042 111 000 622", desc: "Muslim Commercial Bank main branch providing retail, commercial, corporate and Islamic banking.", website: "https://www.mcb.com.pk" },
  { name: "Allied Bank Main Branch", category: "finance", city: "Karachi", address: "3-Tipu Sultan Road, KDA Scheme 1, Karachi", phone: "021 111 225 225", desc: "Allied Bank Limited branch offering deposits, personal loans, car finance and corporate banking.", website: "https://www.abl.com" },
  { name: "Bank Alfalah Main Branch", category: "finance", city: "Lahore", address: "B.A. Building, 117 Kashmir Block, Allama Iqbal Town, Lahore", phone: "042 111 225 111", desc: "Bank Alfalah premier branch offering retail banking, credit cards, investments and Islamic banking.", website: "https://www.bankalfalah.com" },
  { name: "Faysal Bank Main Branch", category: "finance", city: "Karachi", address: "Faysal House, ST-02, Shahrah-e-Faisal, Karachi", phone: "021 111 321 321", desc: "Faysal Bank Islamic and conventional branch offering deposits, lending, trade and digital banking.", website: "https://www.faysalbank.com" },
  { name: "Askari Bank Branch", category: "finance", city: "Rawalpindi", address: "Askari Plaza, Blue Area, Rawalpindi", phone: "051 111 000 787", desc: "Askari Bank providing personal, business and defence banking, Islamic products and locker facilities.", website: "https://www.askaribank.com" },
  { name: "Standard Chartered Main Branch", category: "finance", city: "Karachi", address: "I.I. Chundrigar Road, Karachi", phone: "021 111 002 002", desc: "Standard Chartered branch offering priority banking, credit cards, wealth management and forex services.", website: "https://www.sc.com/pk" },
  { name: "Bank Islami Pakistan", category: "finance", city: "Karachi", address: "11th Floor, Emerald Tower, Clifton, Karachi", phone: "021 111 247 111", desc: "Full-service Islamic bank offering Shariah-compliant deposits, home finance and auto finance.", website: "https://bankislami.com.pk" },
  { name: "Dubai Islamic Bank Pakistan", category: "finance", city: "Karachi", address: "Hassan Chambers, DC-7, Block 7, Kehkashan, Clifton, Karachi", phone: "021 111 786 342", desc: "Islamic banking subsidiary offering Riba-free deposits, cards, home financing and Sukuk investments.", website: "https://www.dibpak.com" },
  { name: "Al Baraka Bank Pakistan", category: "finance", city: "Karachi", address: "Al Baraka House, 162 Bangalore Town, Shahrah-e-Faisal, Karachi", phone: "021 111 113 442", desc: "Shariah-compliant commercial bank offering deposits, consumer finance and corporate banking.", website: "https://www.albaraka.com.pk" },
  { name: "EFU Life Insurance", category: "finance", city: "Karachi", address: "112 State Life Building No. 1, I.I. Chundrigar Road, Karachi", phone: "021 111 338 338", desc: "Leading life insurance company offering protection, savings, investment-linked and Takaful plans.", website: "https://www.efulife.com" },
  { name: "Adamjee Insurance", category: "finance", city: "Lahore", address: "Adamjee House, 80/A, Block E/1, Gulberg III, Lahore", phone: "042 111 111 005", desc: "Pakistan largest general insurance company offering motor, fire, marine, travel and health covers.", website: "https://www.adamjeeinsurance.com" },
  { name: "Jubilee General Insurance", category: "finance", city: "Karachi", address: "74/1-A, Lalazar, M.T. Khan Road, Karachi", phone: "021 111 654 111", desc: "General insurance provider for motor, health, travel, property, marine and engineering risks.", website: "https://www.jubileegeneral.com.pk" },
  { name: "State Life Insurance", category: "finance", city: "Karachi", address: "Dr. Ziauddin Ahmed Road, Karachi", phone: "021 9920 2800", desc: "Pakistan largest life insurer offering life, health, pensions and Group plans for individuals and corporates.", website: "https://www.statelife.com.pk" },
  { name: "Easypaisa Corporate Office", category: "finance", city: "Islamabad", address: "Telenor HQ, 345-F, Phase 8, Bahria Town, Rawalpindi", phone: "051 111 003 737", desc: "Mobile financial services platform offering wallet, payments, bill pay and savings through the Easypaisa app.", website: "https://easypaisa.com.pk" },

  // ====================================================================
  // TRAVEL AND TOURISM (21)
  // ====================================================================
  { name: "Travel Waljis", category: "travel", city: "Islamabad", address: "10-Khayaban-e-Suhrwardy, Aabpara, Islamabad", phone: "051 287 8342", desc: "IATA-accredited travel agency offering airline ticketing, Umrah packages, Europe tours and visa services.", website: "https://www.waljis.com" },
  { name: "Sitara Travel Consultants", category: "travel", city: "Karachi", address: "Shaheen Complex, M.R. Kiyani Road, Karachi", phone: "021 3565 1234", desc: "Full-service travel agency for air tickets, hotel bookings, Umrah and Hajj packages and international tours.", website: "https://sitaratravel.com" },
  { name: "Lahore Tour Specialists", category: "travel", city: "Lahore", address: "Fortress Stadium, Lahore Cantt", phone: "042 3666 0505", desc: "Local and international tour operator for Northern Areas, Turkey, Dubai, Azerbaijan and Saudi Arabia." },
  { name: "Karakoram Explorers", category: "travel", city: "Skardu", address: "Main Bazaar, Skardu City", phone: "0581 4600 100", desc: "Adventure tourism company offering Deosai, K2 Base Camp, Shigar Fort and Hunza trekking expeditions." },
  { name: "PIA Head Office", category: "travel", city: "Karachi", address: "PIA Building, Jinnah International Airport, Karachi", phone: "021 111 786 786", desc: "Pakistan International Airlines - national carrier operating domestic and international flights.", website: "https://www.piac.com.pk" },
  { name: "Airblue Head Office", category: "travel", city: "Islamabad", address: "Airblue Building, G-9 Markaz, Islamabad", phone: "051 111 247 258", desc: "Pakistani private airline operating domestic and Middle East flights with Airbus fleet.", website: "https://www.airblue.com" },
  { name: "Serene Air Head Office", category: "travel", city: "Islamabad", address: "Serene Air Building, Islamabad International Airport", phone: "051 111 737 363", desc: "Domestic and international airline offering premium service to Karachi, Lahore, Dubai, Jeddah and Riyadh.", website: "https://sereneair.com" },
  { name: "AirSial Head Office", category: "travel", city: "Sialkot", address: "AirSial House, Sialkot International Airport Road, Sialkot", phone: "051 111 247 742", desc: "Sialkot-based airline offering domestic flights and international service to the Gulf and Saudi Arabia.", website: "https://airsial.com" },
  { name: "Fly Jinnah Office", category: "travel", city: "Karachi", address: "Fly Jinnah HQ, Karachi Jinnah Terminal, Karachi", phone: "021 111 359 359", desc: "Low-cost carrier offering domestic and international flights with budget fares and online booking.", website: "https://www.flyjinnah.com" },
  { name: "Bookme Office", category: "travel", city: "Lahore", address: "23-C, MM Alam Road, Gulberg, Lahore", phone: "042 111 266 563", desc: "Online booking platform for cinema, bus, air tickets, hotels and events across Pakistan.", website: "https://bookme.pk" },
  { name: "Sastaticket HQ", category: "travel", city: "Karachi", address: "The Forum, 1-R, Block 9, Clifton, Karachi", phone: "021 111 727 8425", desc: "Online travel agency offering cheap flight, hotel, Umrah, and tour package bookings nationwide.", website: "https://www.sastaticket.pk" },
  { name: "Safari Travel Services", category: "travel", city: "Islamabad", address: "Jinnah Avenue, Blue Area, Islamabad", phone: "051 282 3421", desc: "IATA travel agency specialising in business travel, luxury tours and MICE for corporate clients.", website: "https://safaritravel.com.pk" },
  { name: "Travel Solutions Pakistan", category: "travel", city: "Karachi", address: "Progressive Plaza, Beaumont Road, Civil Lines, Karachi", phone: "021 3566 9000", desc: "Corporate and leisure travel agency offering air ticketing, visa processing and holiday packages.", website: "https://www.travelsolutions.com.pk" },
  { name: "Silk Road Travel", category: "travel", city: "Lahore", address: "Model Town, Lahore", phone: "042 3591 2525", desc: "Boutique adventure travel operator for Silk Route, Central Asia, Iran and Northern Pakistan tours." },
  { name: "Pearl Continental Karachi", category: "travel", city: "Karachi", address: "Club Road, Karachi", phone: "021 111 505 505", desc: "Five-star Pearl Continental Hotel with 300+ rooms, banquet halls, fine-dining and business facilities.", website: "https://www.pchotels.com" },
  { name: "Avari Lahore", category: "travel", city: "Lahore", address: "87-Mall Road, Lahore", phone: "042 111 282 747", desc: "Landmark five-star hotel with luxury rooms, multiple restaurants, spa and convention facilities.", website: "https://avari.com" },
  { name: "Serena Hotel Islamabad", category: "travel", city: "Islamabad", address: "Khayaban-e-Suhrwardy, Islamabad", phone: "051 111 133 133", desc: "Five-star Serena Hotel offering luxury rooms, gardens, spa, fine-dining and event facilities.", website: "https://www.serenahotels.com" },
  { name: "Hunza Serena Inn", category: "travel", city: "Hunza", address: "Central Hunza, Aliabad, Gilgit-Baltistan", phone: "05813 455 107", desc: "Boutique Serena inn overlooking Rakaposhi and Ultar peaks offering guided Hunza Valley tours.", website: "https://www.serenahotels.com" },
  { name: "Shangrila Resort Skardu", category: "travel", city: "Skardu", address: "Lower Kachura Lake, Skardu, Gilgit-Baltistan", phone: "0345 853 7788", desc: "Iconic lakeside resort at Heaven on Earth Lake offering wooden chalets and scenic Skardu tours.", website: "https://shangrilaresorts.com.pk" },
  { name: "Movenpick Karachi", category: "travel", city: "Karachi", address: "Club Road, Karachi", phone: "021 3563 3333", desc: "Five-star international hotel with 409 rooms, multiple restaurants, ballrooms and a spa overlooking the Arabian Sea." },
  { name: "Faletti Hotel Lahore", category: "travel", city: "Lahore", address: "24-Egerton Road, Lahore", phone: "042 3636 3946", desc: "Historic five-star hotel in the heart of Lahore offering luxury suites, bar, spa and fine-dining." },

  // ====================================================================
  // BEAUTY AND WELLNESS (20)
  // ====================================================================
  { name: "Nabila Salon DHA", category: "beauty", city: "Karachi", address: "N-Gents, 22nd Street, Khayaban-e-Shahbaz, DHA Phase 6, Karachi", phone: "021 3531 0001", desc: "Award-winning salon offering bridal makeup, hair styling, colour, skin and nail services by Nabila team.", website: "https://www.n-nabila.com" },
  { name: "Depilex Smile Studio Liberty", category: "beauty", city: "Lahore", address: "10-Commercial Zone, Liberty Market, Gulberg, Lahore", phone: "042 3578 1111", desc: "Full-service beauty salon offering facials, laser treatments, bridal packages and dental smile makeovers.", website: "https://depilex.com" },
  { name: "Natasha Beauty Salon F-7", category: "beauty", city: "Islamabad", address: "F-7 Markaz, Islamabad", phone: "051 265 2020", desc: "Signature salon for haircuts, hair colour, keratin, facials, waxing, threading and bridal makeovers." },
  { name: "Toni and Guy DHA Karachi", category: "beauty", city: "Karachi", address: "Zamzama Boulevard, DHA Phase 5, Karachi", phone: "021 3539 1000", desc: "International hair and beauty salon offering precision haircuts, advanced colour and styling.", website: "https://toniandguy.pk" },
  { name: "Sabs The Salon Lahore", category: "beauty", city: "Lahore", address: "14-A, Main Gulberg, Lahore", phone: "042 3571 6166", desc: "Legendary beauty salon for brides, hair, makeup, skin care and grooming services." },
  { name: "Khawar Riaz Salon", category: "beauty", city: "Lahore", address: "E-1, Gulberg III, Lahore", phone: "042 3587 5575", desc: "Celebrity hair and makeup salon specialising in bridal styling, hair colour and luxury grooming services." },
  { name: "Kashees Beauty Parlour", category: "beauty", city: "Karachi", address: "Shaheed-e-Millat Road, Karachi", phone: "021 111 527 433", desc: "Famous bridal studio with signature makeup styles, mehndi setups and hair-styling services.", website: "https://kashees.com" },
  { name: "Tariq Amin Hair Academy", category: "beauty", city: "Karachi", address: "Zamzama Commercial Lane 1, DHA Phase 5, Karachi", phone: "021 3536 5550", desc: "Premier hair salon and training academy for professional stylists, offering cuts, colour and creative styling." },
  { name: "Nadia Hussain Salon", category: "beauty", city: "Karachi", address: "Bukhari Commercial Lane 11, DHA Phase 6, Karachi", phone: "021 3531 1181", desc: "Celebrity salon offering bridal makeovers, photoshoot makeup, facials and hair services." },
  { name: "Mahin Hussain Salon", category: "beauty", city: "Karachi", address: "DHA Phase 6, Karachi", phone: "021 3531 2222", desc: "Upscale salon offering hair, makeup, threading, facials and bridal packages." },
  { name: "Scentsation Spa and Salon", category: "beauty", city: "Islamabad", address: "F-10 Markaz, Islamabad", phone: "051 229 3310", desc: "Full-service ladies salon and day spa offering body massage, facials, hair treatments and manicures." },
  { name: "Barber Box", category: "beauty", city: "Lahore", address: "Y-Block, DHA Phase 3, Lahore", phone: "042 3522 1717", desc: "Modern barber studio for men offering haircuts, beard grooming, facial treatments and head massage." },
  { name: "Allure Beauty Lounge", category: "beauty", city: "Karachi", address: "Phase 8, DHA, Karachi", phone: "021 3584 9292", desc: "Premium beauty lounge offering hair, nails, advanced facials, laser hair removal and bridal packages." },
  { name: "Beauty World Hayatabad", category: "beauty", city: "Peshawar", address: "Hayatabad Phase 3, Peshawar", phone: "091 581 6262", desc: "Ladies-only beauty salon offering haircut, facial, threading, bridal makeup and party hairstyling." },
  { name: "Ambreens Salon", category: "beauty", city: "Rawalpindi", address: "Satellite Town, Rawalpindi", phone: "051 484 5151", desc: "Ladies salon offering threading, hair colour, hydra facial, keratin treatment and bridal packages." },
  { name: "Raana Khan Studio", category: "beauty", city: "Lahore", address: "Model Town, Lahore", phone: "042 3516 4100", desc: "Bridal specialist studio offering engagement, mehndi, barat and valima makeup packages." },
  { name: "Mashals Signature Salon", category: "beauty", city: "Islamabad", address: "F-11 Markaz, Islamabad", phone: "051 229 1188", desc: "Upscale salon for haircuts, hair colour, hydra-facial, bridal makeup and premium skin treatments." },
  { name: "Mominas Beauty Saloon", category: "beauty", city: "Faisalabad", address: "Madina Town, Faisalabad", phone: "041 854 9090", desc: "Ladies beauty parlour offering facial, threading, waxing, bridal makeup and mehndi services." },
  { name: "Barbers Lounge", category: "beauty", city: "Karachi", address: "Zamzama, DHA Phase 5, Karachi", phone: "021 3536 4444", desc: "Mens grooming lounge offering haircuts, beard styling, hot towel shaves and scalp treatments." },
  { name: "Glow Aesthetics Clinic", category: "beauty", city: "Lahore", address: "Phase 5, DHA, Lahore", phone: "042 3521 0000", desc: "Medical aesthetic clinic offering Botox, fillers, laser hair removal, skin rejuvenation and acne treatment." },

  // ====================================================================
  // LOGISTICS AND TRANSPORT (17)
  // ====================================================================
  { name: "TCS Express and Logistics", category: "logistics", city: "Karachi", address: "TCS Head Office, Plot 113, Sector 24, Korangi, Karachi", phone: "021 111 123 456", desc: "Pakistan leading courier and logistics company offering overnight delivery, e-commerce and freight services.", website: "https://www.tcsexpress.com" },
  { name: "Leopards Courier Services", category: "logistics", city: "Lahore", address: "88-C, Block E, Main Boulevard, Gulberg III, Lahore", phone: "042 111 300 786", desc: "Nationwide domestic and international courier service with same-day delivery and cash-on-delivery solutions.", website: "https://www.leopardscourier.com" },
  { name: "M and P Express Logistics", category: "logistics", city: "Hyderabad", address: "Auto Bhan Road, Latifabad, Hyderabad", phone: "022 381 1011", desc: "Muller and Phipps logistics offering parcel delivery, warehousing and cash-on-delivery for online stores.", website: "https://www.mulphilog.com" },
  { name: "DHL Express Pakistan", category: "logistics", city: "Karachi", address: "Jinnah International Airport, Karachi", phone: "021 111 345 345", desc: "Global express courier offering international document, parcel and freight delivery to 220+ countries.", website: "https://www.dhl.com/pk" },
  { name: "FedEx Pakistan", category: "logistics", city: "Karachi", address: "Plot 28, Sector 21, Korangi Industrial Area, Karachi", phone: "021 111 226 333", desc: "International courier offering express, priority and economy shipping with real-time tracking.", website: "https://www.fedex.com" },
  { name: "UPS Pakistan", category: "logistics", city: "Karachi", address: "Khayaban-e-Shaheen, Phase 6, DHA, Karachi", phone: "021 111 100 888", desc: "Global express carrier handling international parcels, documents and supply chain solutions.", website: "https://www.ups.com" },
  { name: "Pakistan Post Headquarters", category: "logistics", city: "Islamabad", address: "GPO Building, G-6, Islamabad", phone: "051 921 1234", desc: "National postal operator offering letters, parcels, UMS, EMS and money orders across Pakistan.", website: "https://www.pakpost.gov.pk" },
  { name: "Bykea", category: "logistics", city: "Karachi", address: "Ground Floor, Bahria Complex III, M.T. Khan Road, Karachi", phone: "0304 111 1151", desc: "Bike-based app offering ride-hailing, parcel delivery, food delivery and mobile wallet top-ups.", website: "https://bykea.com" },
  { name: "Daewoo Express Head Office", category: "logistics", city: "Lahore", address: "Thokar Niaz Baig, Lahore", phone: "042 111 007 008", desc: "Pakistan largest private intercity bus service with gold-class, business-class and cargo courier.", website: "https://www.daewoo.com.pk" },
  { name: "Faisal Movers", category: "logistics", city: "Lahore", address: "Thokar Niaz Baig Bus Stand, Lahore", phone: "042 111 222 645", desc: "Popular intercity luxury bus service with hostess-assisted executive-class travel across Pakistan.", website: "https://faisalmovers.com" },
  { name: "Skyways", category: "logistics", city: "Rawalpindi", address: "Pirwadhai General Bus Stand, Rawalpindi", phone: "051 111 759 799", desc: "Bus service provider offering executive, business and standard intercity coaches across Pakistan." },
  { name: "Niazi Express", category: "logistics", city: "Lahore", address: "Thokar Niaz Baig, Lahore", phone: "042 3541 2121", desc: "Intercity bus service operating between Lahore, Islamabad, Karachi, Multan and Peshawar." },
  { name: "Pakistan Railways Karachi Cantt", category: "logistics", city: "Karachi", address: "Karachi Cantonment Station, Karachi", phone: "021 9920 1139", desc: "Karachi Cantt railway station offering passenger, freight and parcel services on main lines.", website: "https://www.pakrail.gov.pk" },
  { name: "Careem Pakistan HQ", category: "logistics", city: "Karachi", address: "Teen Talwar, Clifton, Karachi", phone: "021 111 227 336", desc: "Super-app offering Careem car rides, bike rides, food delivery, deliveries and pay services.", website: "https://www.careem.com" },
  { name: "InDrive Pakistan Office", category: "logistics", city: "Lahore", address: "Main Boulevard, Gulberg, Lahore", phone: "0304 111 7463", desc: "Ride-hailing platform offering price-negotiation between riders and drivers in major Pakistani cities.", website: "https://indrive.com" },
  { name: "Yango Pakistan", category: "logistics", city: "Karachi", address: "Shahrah-e-Faisal, Karachi", phone: "0304 111 9264", desc: "Global ride-hailing platform offering economy, comfort and business cars in Karachi, Lahore and Islamabad.", website: "https://yango.com" },
  { name: "Cargo Express", category: "logistics", city: "Gujranwala", address: "G.T. Road, Gujranwala", phone: "055 385 9999", desc: "Local freight and cargo handling firm offering full-truck-load, warehousing and distribution services." },
]
